// Fallback theme to avoid undefined property errors
export const theme = {
  dark: false,
  roundness: 4,
  version: 3,
  isV3: true,
  colors: {
    primary: '#f59e0b',
    primaryContainer: '#fef3c7',
    secondary: '#374151',
    secondaryContainer: '#f3f4f6',
    tertiary: '#f59e0b',
    tertiaryContainer: '#fef3c7',
    surface: '#ffffff',
    surfaceVariant: '#f9fafb',
    surfaceDisabled: '#f3f4f6',
    background: '#ffffff',
    error: '#ef4444',
    errorContainer: '#fecaca',
    onPrimary: '#ffffff',
    onPrimaryContainer: '#92400e',
    onSecondary: '#ffffff',
    onSecondaryContainer: '#1f2937',
    onTertiary: '#ffffff',
    onTertiaryContainer: '#92400e',
    onSurface: '#1f2937',
    onSurfaceVariant: '#6b7280',
    onSurfaceDisabled: '#9ca3af',
    onError: '#ffffff',
    onErrorContainer: '#7f1d1d',
    onBackground: '#1f2937',
    outline: '#d1d5db',
    outlineVariant: '#e5e7eb',
    inverseSurface: '#374151',
    inverseOnSurface: '#f9fafb',
    inversePrimary: '#fbbf24',
    elevation: {
      level0: 'transparent',
      level1: '#ffffff',
      level2: '#f9fafb',
      level3: '#f3f4f6',
      level4: '#f3f4f6',
      level5: '#e5e7eb',
    },
  },
};